[package]
name = "routerify-csrf"
version = "0.1.0"
authors = ["jdisa <jdisa@JISAACS-LAPTOP>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
